// WolfMark.swift
//
// Wolf-head silhouette used as the brand mark. The 22pt template is the
// canonical menu bar icon; the full mark is used in About + paywall headers.
// Geometry mirrors the SVG path in docs/design/HowlAlert.html lines 671–678.
//
// NB: this Swift path is intentionally a faithful placeholder. The
// production menu-bar icon ships as a template PNG generated by Apple's
// Icon Composer (see Phase 0 manual prep). This vector lets previews and
// non-menu-bar surfaces render the mark without a bundled asset.

import SwiftUI

public struct WolfMark: View {
    private let tint: Color
    private let size: CGFloat

    public init(tint: Color = .howlCyan500, size: CGFloat = 22) {
        self.tint = tint
        self.size = size
    }

    public var body: some View {
        WolfShape()
            .stroke(tint, style: StrokeStyle(lineWidth: 1.6, lineCap: .round, lineJoin: .round))
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

private struct WolfShape: Shape {
    func path(in rect: CGRect) -> Path {
        // Mapped to a 22×22 viewBox, scaled to the receiver's frame.
        let s = min(rect.width, rect.height) / 22
        func p(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
            CGPoint(x: rect.minX + x * s, y: rect.minY + y * s)
        }
        var path = Path()
        // Outer head outline — ears, jaw, snout — approximation of the
        // canonical wolf head silhouette template.
        path.move(to: p(3, 5))      // left ear tip
        path.addLine(to: p(5, 2))
        path.addLine(to: p(8, 6))   // left ear inner
        path.addLine(to: p(14, 6))  // right ear inner
        path.addLine(to: p(17, 2))
        path.addLine(to: p(19, 5))  // right ear tip
        path.addLine(to: p(20, 11)) // right cheek
        path.addLine(to: p(17, 16)) // jaw right
        path.addLine(to: p(13, 19)) // snout right
        path.addLine(to: p(11, 20)) // chin
        path.addLine(to: p(9, 19))  // snout left
        path.addLine(to: p(5, 16))  // jaw left
        path.addLine(to: p(2, 11))  // left cheek
        path.closeSubpath()

        // Eye marks.
        path.addEllipse(in: CGRect(
            origin: p(7.5, 10),
            size: CGSize(width: 1.5 * s, height: 1.5 * s)
        ))
        path.addEllipse(in: CGRect(
            origin: p(13, 10),
            size: CGSize(width: 1.5 * s, height: 1.5 * s)
        ))
        return path
    }
}
